// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn7KDwtaHmW4ielE3ifJB9gl3Y3VbvOeo',
    appId: '1:267921587505:web:4f65250ee34c5a3b6f0410',
    messagingSenderId: '267921587505',
    projectId: 'smarttourism-5e508',
    authDomain: 'smarttourism-5e508.firebaseapp.com',
    storageBucket: 'smarttourism-5e508.firebasestorage.app',
    measurementId: 'G-HL14WZX4XC'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuwT6u4gFU2IquVHvXkPmxwIkwXb7cBwI',
    appId: '1:267921587505:android:4ac85be2e46f01576f0410',
    messagingSenderId: '267921587505',
    projectId: 'smarttourism-5e508',
    storageBucket: 'smarttourism-5e508.firebasestorage.app'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF6s5mv1gvCjx98EcqDeR0UxuUVPKLMBs',
    appId: '1:267921587505:ios:2fd29c3450b102e16f0410',
    messagingSenderId: '267921587505',
    projectId: 'smarttourism-5e508',
    storageBucket: 'smarttourism-5e508.firebasestorage.app',
    iosBundleId: 'com.example.smartTourism',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF6s5mv1gvCjx98EcqDeR0UxuUVPKLMBs',
    appId: '1:267921587505:ios:2fd29c3450b102e16f0410',
    messagingSenderId: '267921587505',
    projectId: 'smarttourism-5e508',
    storageBucket: 'smarttourism-5e508.firebasestorage.app',
    iosBundleId: 'com.example.smartTourism',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn7KDwtaHmW4ielE3ifJB9gl3Y3VbvOeo',
    appId: '1:267921587505:web:a32cc96637f9185e6f0410',
    messagingSenderId: '267921587505',
    projectId: 'smarttourism-5e508',
    authDomain: 'smarttourism-5e508.firebaseapp.com',
    storageBucket: 'smarttourism-5e508.firebasestorage.app',
    measurementId: 'G-NN3F9V208V',
  );
}
